-- Connect to userevents database (default per your env vars)
-- Create users table if not exists

CREATE TABLE IF NOT EXISTS public.users (
    key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.users REPLICA IDENTITY FULL;

-- Insert 20 sample users
INSERT INTO public.users (name, address)
VALUES
('John Doe', '123 Main St, Rabat'),
('Fatima Zahra', '456 Avenue Hassan II, Casablanca'),
('Ali Mansour', '789 Boulevard Zerktouni, Marrakech'),
('Sara Benali', '22 Rue de la Liberté, Fès'),
('Omar El Idrissi', '33 Avenue Mohammed V, Tangier'),
('Leila Amrani', '44 Boulevard Med V, Rabat'),
('Hassan Naji', '55 Street of Roses, Agadir'),
('Meryem El Fassi', '66 Avenue of Stars, Casablanca'),
('Khalid Othmani', '77 Boulevard Al Massira, Marrakech'),
('Nadia Chouki', '88 Street Jasmine, Rabat'),
('Youssef Bouazizi', '99 Avenue Liberty, Casablanca'),
('Imane El Khalfi', '101 Boulevard Sunrise, Tangier'),
('Rachid Bahraoui', '202 Street of Palm Trees, Fès'),
('Salma Idrissi', '303 Avenue Blue Sky, Marrakech'),
('Adil Najib', '404 Boulevard Ocean, Rabat'),
('Zineb Bennis', '505 Street Jasmine, Casablanca'),
('Tarik Elmouden', '606 Avenue Moonlight, Tangier'),
('Samira El Haj', '707 Boulevard Sunset, Agadir'),
('Mohamed Bouazza', '808 Street Cedar, Rabat'),
('Laila Haddad', '909 Avenue Olive, Casablanca');

-- Connect to postgres default DB to create orderevents DB (if not exists)
CREATE DATABASE orderevents;

-- Connect to orderevents DB
\c orderevents;

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- no FK cross-database, ensure app-level integrity
    order_date TIMESTAMP DEFAULT NOW(),
    amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.orders REPLICA IDENTITY FULL;

-- Insert 20 sample orders
INSERT INTO public.orders (order_date, amount, status)
VALUES
(NOW(), 120.50, 'processing'),
(NOW(), 89.99, 'shipped'),
(NOW(), 210.00, 'delivered'),
(NOW(), 45.25, 'processing'),
(NOW(), 75.00, 'cancelled'),
(NOW(), 150.50, 'delivered'),
(NOW(), 220.00, 'shipped'),
(NOW(), 95.00, 'processing'),
(NOW(), 300.75, 'delivered'),
(NOW(), 110.00, 'processing'),
(NOW(), 67.50, 'shipped'),
(NOW(), 80.25, 'processing'),
(NOW(), 99.99, 'delivered'),
(NOW(), 130.40, 'cancelled'),
(NOW(), 55.00, 'shipped'),
(NOW(), 77.75, 'processing'),
(NOW(), 45.00, 'delivered'),
(NOW(), 88.80, 'shipped'),
(NOW(), 123.00, 'processing'),
(NOW(), 60.50, 'delivered');
