services:

    broker:
      image: bitnami/kafka:4.0.0
      hostname: broker
      container_name: broker
      restart: unless-stopped
      ports:
        - ${KAFKA_BROKER_PORT}:9092
      volumes:
        - kafka-data:/bitnami/kafka/data
      healthcheck:
        test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/9092'"]
        interval: 20s
        timeout: 5s
        retries: 5
        start_period: 120s